FROM openjdk:17

WORKDIR /app

COPY /target/marketplace-0.0.1-SNAPSHOT.jar /app/marketplace-0.0.1-SNAPSHOT.jar

# Specify the command to run on container startup
CMD ["java", "-jar", "marketplace-0.0.1-SNAPSHOT.jar"]
