INSERT INTO category (name, description) VALUES ('House Painting', 'Interior and exterior painting services for residential properties');
INSERT INTO category (name, description) VALUES ('Commercial Cleaning', 'Professional cleaning services for commercial spaces');
INSERT INTO category (name, description) VALUES ('Landscaping', 'Designing and maintaining outdoor spaces');
INSERT INTO category (name, description) VALUES ('Carpet Cleaning', 'Deep cleaning and maintenance of carpets and rugs');
INSERT INTO category (name, description) VALUES ('Plumbing Services', 'Installation and repair of plumbing systems');
INSERT INTO category (name, description) VALUES ('Electrical Services', 'Installation and repair of electrical systems');
INSERT INTO category (name, description) VALUES ('Roof Repair', 'Fixing and maintaining roofs on residential and commercial buildings');
INSERT INTO category (name, description) VALUES ('Pest Control', 'Extermination and prevention of pests and insects');
INSERT INTO category (name, description) VALUES ('Home Renovation', 'Remodeling and renovating residential properties');
INSERT INTO category (name, description) VALUES ('Window Cleaning', 'Cleaning and maintaining windows for homes and businesses');
INSERT INTO category (name, description) VALUES ('Car Detailing', 'Thorough cleaning and maintenance of vehicles');
INSERT INTO category (name, description) VALUES ('Gardening Services', 'Planting, pruning, and maintaining gardens');
INSERT INTO category (name, description) VALUES ('Appliance Repair', 'Fixing and maintaining household appliances');
INSERT INTO category (name, description) VALUES ('Pool Cleaning', 'Cleaning and maintaining swimming pools');
INSERT INTO category (name, description) VALUES ('Junk Removal', 'Removal and disposal of unwanted items and debris');
INSERT INTO category (name, description) VALUES ('HVAC Services', 'Heating, ventilation, and air conditioning services');
INSERT INTO category (name, description) VALUES ('Car Maintenance', 'Regular maintenance services for vehicles');
INSERT INTO category (name, description) VALUES ('Catering Services', 'Providing food and beverage services for events');
INSERT INTO category (name, description) VALUES ('Interior Design', 'Planning and designing interior spaces for homes and offices');
INSERT INTO category (name, description) VALUES ('Moving Services', 'Assistance with packing and relocating belongings');
