INSERT INTO city (name, zip_code, address) VALUES
('Sofia', 1000, 'Sofia, Bulgaria'),
('Plovdiv', 4000, 'Plovdiv, Bulgaria'),
('Varna', 9000, 'Varna, Bulgaria'),
('Burgas', 8000, 'Burgas, Bulgaria'),
('Ruse', 7000, 'Ruse, Bulgaria'),
('Stara Zagora', 6000, 'Stara Zagora, Bulgaria'),
('Pleven', 5800, 'Pleven, Bulgaria'),
('Sliven', 8800, 'Sliven, Bulgaria'),
('Dobrich', 9300, 'Dobrich, Bulgaria'),
('Shumen', 9700, 'Shumen, Bulgaria'),
('Pernik', 2300, 'Pernik, Bulgaria'),
('Yambol', 8600, 'Yambol, Bulgaria'),
('Haskovo', 6300, 'Haskovo, Bulgaria'),
('Pazardzhik', 4400, 'Pazardzhik, Bulgaria'),
('Blagoevgrad', 2700, 'Blagoevgrad, Bulgaria'),
('Veliko Tarnovo', 5000, 'Veliko Tarnovo, Bulgaria'),
('Gabrovo', 5300, 'Gabrovo, Bulgaria'),
('Vratsa', 3000, 'Vratsa, Bulgaria'),
('Dimitrovgrad', 6400, 'Dimitrovgrad, Bulgaria'),
('Vidin', 3700, 'Vidin, Bulgaria'),
('Kardzhali', 6600, 'Kardzhali, Bulgaria'),
('Montana', 3400, 'Montana, Bulgaria'),
('Targovishte', 7700, 'Targovishte, Bulgaria'),
('Silistra', 7500, 'Silistra, Bulgaria'),
('Lovech', 5500, 'Lovech, Bulgaria'),
('Kazanlak', 6100, 'Kazanlak, Bulgaria'),
('Kyustendil', 2500, 'Kyustendil, Bulgaria');
